### ISSUE TITLE
If there are too many directories, , it will not be displayed completely, and the font is too small, can it be set to scroll mode?

### ISSUE THREAD

**Issue by zhl111** [curtgrimes/obsidian-floating-toc-plugin#1]
![image](https://user-images.githubusercontent.com/29135984/150666104-db44c20b-4642-431d-803d-82a4131165c4.png)

**Comment by cumany** [comment]
I fixed the bug, which was triggered by a css style
Please modify the style.css file in the plugin directory：
```css
.floating-toc[data-v-3bdd42b2] {
  list-style: none;
  margin: 0;
  padding: 0.1rem;
  position: absolute;
  top: 40px;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  overflow: hidden;
  bottom: 40px;
  width: 2rem;
}
.floating-toc[data-reveal=true][data-v-3bdd42b2] {
  width: auto;
  overflow: auto;
}
.floating-toc[data-reveal=true][data-v-3bdd42b2]::-webkit-scrollbar {
                display: none;
            }


```
